remove rest_framework_swagger 暂时使[build 45](https://travis-ci.org/killuavx/game_center/builds/11346845) [commit 0d1f83f (develop)](http://github.com/killuavx/game_center/commit/0d1f83f8e4ad2b6d32b78803b00f3701881fe2f4)获得通过
File "/home/travis/virtualenv/python3.3/lib/python3.3/site-packages/rest_framework_swagger/docgenerator.py", line 7, in <module>
    from rest_framework.utils.formatting import get_view_name, \
ImportError: cannot import name get_view_name
--------------

  File "/home/travis/virtualenv/python3.3/lib/python3.3/site-packages/django/core/urlresolvers.py", line 340, in urlconf_module
    return self._urlconf_module
AttributeError: RegexURLResolver object has no attribute _urlconf_module